import { NextRequest } from 'next/server';
import { connectDB } from '@/lib/mongodb';
import { Project, Spec } from '@/backend/models';
import { requirePermission } from '@/lib/auth';
import {
  successResponse,
  withErrorHandling,
  notFoundError,
} from '@/lib/api-utils';
import { claudeClient } from '@/backend/services/claude-client';
import { publishActivityLog } from '@/lib/pubsub';
import { EventType } from '@/backend/models';

interface RouteContext {
  params: {
    projectId: string;
  };
}

/**
 * POST /api/projects/[projectId]/generate-specs
 * Generate specifications for a project using Claude with extended thinking
 */
export const POST = withErrorHandling(async (
  request: NextRequest,
  context: RouteContext
) => {
  await requirePermission('SPEC_CREATE');
  await connectDB();

  const { projectId } = context.params;

  // Find the project
  const project = await Project.findById(projectId);

  if (!project) {
    return notFoundError('Project');
  }

  // Get existing specs to avoid duplication
  const existingSpecs = await Spec.find({ projectId }).select('name description');

  // Generate specs using Claude with extended thinking
  console.log('Generating specs for project:', project.name);

  let generatedSpecs;
  try {
    // Emit progress updates via WebSocket
    const progressCallback = (text: string) => {
      if (global.io) {
        global.io.to(`project:${projectId}`).emit('ai:progress', {
          type: 'spec_generation',
          text,
          timestamp: new Date().toISOString(),
        });
      }
    };

    generatedSpecs = await claudeClient.generateSpecifications(
      project.name,
      project.description || 'No description provided',
      project.architecture,
      existingSpecs.map(s => ({ name: s.name, description: s.description })),
      progressCallback
    );
  } catch (error: any) {
    console.error('Claude API error:', error);

    // Check for common API errors
    if (error.status === 401 || error.message?.includes('authentication')) {
      throw new Error('Invalid Anthropic API key. Please check your ANTHROPIC_API_KEY environment variable.');
    }

    if (error.status === 400 && error.message?.includes('credit balance')) {
      throw new Error('Your Anthropic account has insufficient credits. Please add credits at https://console.anthropic.com/settings/plans');
    }

    throw new Error(`Failed to generate specifications: ${error.message || 'Unknown error'}`);
  }

  console.log(`Generated ${generatedSpecs.length} specs:`, generatedSpecs.map(s => s.title));

  // Get the last spec number for this project
  const lastSpec = await Spec.findOne({ projectId })
    .sort({ specNumber: -1 })
    .select('specNumber');

  let specNumber = lastSpec ? lastSpec.specNumber + 1 : 1;

  // Create all specs in the database
  const createdSpecs = [];

  for (const specData of generatedSpecs) {
    const spec = await Spec.create({
      projectId,
      specNumber,
      title: specData.title,
      description: specData.description,
      priority: specData.priority,
      requirements: {},
      currentPhase: 'REQUIREMENTS',
      status: 'ACTIVE',
      progress: 0,
    });

    const populatedSpec = await Spec.findById(spec._id)
      .populate('projectId', 'name');

    createdSpecs.push(populatedSpec);

    // Publish activity log
    await publishActivityLog({
      eventType: EventType.SPEC_CREATED,
      specId: spec._id,
      message: `Spec #${specNumber} auto-generated: ${specData.title}`,
      metadata: { title: specData.title, priority: specData.priority, autoGenerated: true },
    });

    specNumber++;
  }

  // Auto-analyze dependencies after generating specs
  try {
    const allSpecs = await Spec.find({ projectId: context.params.projectId }).lean();
    const specList = allSpecs.map((s: any) => `ID:${s._id} #${s.specNumber} "${s.title}": ${(s.description || '').slice(0, 120)}`).join('\n');
    const prompt = `Analyze these software feature specs and determine build order dependencies.\n\n${specList}\n\nCategorize each spec:\n- "foundation": Core features everything else depends on\n- "recommended": Depends on foundation, can be built in parallel\n- "optional": Enhancement features, built last\n\nRespond ONLY with valid JSON:\n{"specs":[{"id":"<_id>","layer":"foundation"|"recommended"|"optional","dependsOn":["<_id>"]}]}`;

    const { spawn } = await import('child_process');
    const { execSync } = await import('child_process');
    let claudePath = 'claude';
    try { claudePath = execSync('which claude', { encoding: 'utf8' }).trim(); } catch {}

    const result = await new Promise<string>((resolve) => {
      let output = '';
      const env = { ...process.env };
      delete env.ANTHROPIC_API_KEY;
      const proc = spawn(claudePath, ['-p', prompt, '--output-format', 'text'], { env });
      proc.stdout.on('data', (d: Buffer) => output += d.toString());
      proc.on('close', () => resolve(output));
      proc.on('error', () => resolve(''));
    });

    const jsonMatch = result.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      const { specs: analyzed } = JSON.parse(jsonMatch[0]);
      for (const item of analyzed) {
        await Spec.findByIdAndUpdate(item.id, { layer: item.layer, dependsOn: item.dependsOn || [] });
      }
    }
  } catch (e) {
    // Non-fatal - specs are still created even if analysis fails
    console.warn('[generate-specs] Dependency analysis failed:', e);
  }

  return successResponse(
    { specs: createdSpecs, count: createdSpecs.length },
    `Generated ${createdSpecs.length} specifications successfully`,
    201
  );
});
