import { NextRequest } from 'next/server';
import { connectDB } from '@/lib/mongodb';
import { Project, Spec } from '@/backend/models';
import { requirePermission } from '@/lib/auth';
import {
  successResponse,
  withErrorHandling,
  notFoundError,
} from '@/lib/api-utils';
import { claudeClient } from '@/backend/services/claude-client';
import { publishActivityLog } from '@/lib/pubsub';
import { EventType } from '@/backend/models';

interface RouteContext {
  params: {
    projectId: string;
  };
}

/**
 * POST /api/projects/[projectId]/generate-specs
 * Generate specifications for a project using Claude with extended thinking
 */
export const POST = withErrorHandling(async (
  request: NextRequest,
  context: RouteContext
) => {
  await requirePermission('SPEC_CREATE');
  await connectDB();

  const { projectId } = context.params;

  // Find the project
  const project = await Project.findById(projectId);

  if (!project) {
    return notFoundError('Project');
  }

  // Get existing specs to avoid duplication
  const existingSpecs = await Spec.find({ projectId }).select('name description');

  // Generate specs using Claude with extended thinking
  console.log('Generating specs for project:', project.name);

  let generatedSpecs;
  try {
    // Emit progress updates via WebSocket
    const progressCallback = (text: string) => {
      if (global.io) {
        global.io.to(`project:${projectId}`).emit('ai:progress', {
          type: 'spec_generation',
          text,
          timestamp: new Date().toISOString(),
        });
      }
    };

    generatedSpecs = await claudeClient.generateSpecifications(
      project.name,
      project.description || 'No description provided',
      project.architecture,
      existingSpecs.map(s => ({ name: s.name, description: s.description })),
      progressCallback
    );
  } catch (error: any) {
    console.error('Claude API error:', error);

    // Check for common API errors
    if (error.status === 401 || error.message?.includes('authentication')) {
      throw new Error('Invalid Anthropic API key. Please check your ANTHROPIC_API_KEY environment variable.');
    }

    if (error.status === 400 && error.message?.includes('credit balance')) {
      throw new Error('Your Anthropic account has insufficient credits. Please add credits at https://console.anthropic.com/settings/plans');
    }

    throw new Error(`Failed to generate specifications: ${error.message || 'Unknown error'}`);
  }

  console.log(`Generated ${generatedSpecs.length} specs:`, generatedSpecs.map(s => s.title));

  // Get the last spec number for this project
  const lastSpec = await Spec.findOne({ projectId })
    .sort({ specNumber: -1 })
    .select('specNumber');

  let specNumber = lastSpec ? lastSpec.specNumber + 1 : 1;

  // Create all specs in the database
  const createdSpecs = [];

  for (const specData of generatedSpecs) {
    const spec = await Spec.create({
      projectId,
      specNumber,
      title: specData.title,
      description: specData.description,
      priority: specData.priority,
      requirements: {},
      currentPhase: 'REQUIREMENTS',
      status: 'ACTIVE',
      progress: 0,
    });

    const populatedSpec = await Spec.findById(spec._id)
      .populate('projectId', 'name');

    createdSpecs.push(populatedSpec);

    // Publish activity log
    await publishActivityLog({
      eventType: EventType.SPEC_CREATED,
      specId: spec._id,
      message: `Spec #${specNumber} auto-generated: ${specData.title}`,
      metadata: { title: specData.title, priority: specData.priority, autoGenerated: true },
    });

    specNumber++;
  }

  return successResponse(
    { specs: createdSpecs, count: createdSpecs.length },
    `Generated ${createdSpecs.length} specifications successfully`,
    201
  );
});
